### ISSUE TITLE
[Question] Trust Wallet

### ISSUE THREAD

**Issue by Drjacky** [lakshyabatman/Bulk-uploader-NFT#1]
Does it work with TrustWallet as well?

**Comment by lakshyabatman** [comment]
No, only metamask. It's an automation script that uploads for you.

**Comment by Drjacky** [comment]
@lakshyabatman Is it possible to list them too?(set them for sale)

**Comment by lakshyabatman** [comment]
@Drjacky I haven't written a script for that but if you want I write it up for especially as a freelance project?
