### ISSUE TITLE
Question about some file you mentioned in your script

### ISSUE THREAD

**Issue by Terrytsang0618** [lakshyabatman/Bulk-uploader-NFT#2]
May I know the details about "metadata.json" you mentioned on row 102(main.py)?
What should I include in this json? Do I also need to create a json file?
Also, what is the usage of the CSV folder?
Many Thanks.

**Comment by lakshyabatman** [comment]
Ok, I made two parsers. One for CSV and one for JSON, so for JSON you need to have a structure like
```
{
    "0": {
        "Background": "Background #5",
        "Face": "Chad Face #3",
        "Body": "Body #4",
        "Hair": "Sexy Hair #4",
        "skeleton": "Skeleton #1"
    }
}
```

The key should map to the file as well, you can see in the code.
