### ISSUE TITLE
Upload Jpg?

### ISSUE THREAD

**Issue by jephjohnson** [lakshyabatman/Bulk-uploader-NFT#3]
Hi,

Does this just upload the metadata/csv data or the data along with the NFT .jpg/.png/gif?

Also, I’ll buy you a 100 coffees if you’d make a demo video. ;)

**Comment by lakshyabatman** [comment]
XD, sure can do that. Give me some hours and I'll be back.

**Comment by lakshyabatman** [comment]
@jephjohnson can you reach out to me by mail, I'll share the details?

**Comment by jephjohnson** [comment]
> @jephjohnson can you reach out to me by mail, I'll share the details?

Sent you email.
