### ISSUE TITLE
Select Polygon chain instead of Ethereum

### ISSUE THREAD

**Issue by VishnuPJ** [lakshyabatman/Bulk-uploader-NFT#4]
How can I select Polygon chain, since this selects Ethereum by default.

**Comment by VishnuPJ** [comment]
I have figured it out.
`blockchain_button = driver.find_element(By.XPATH, '//*[@id="__next"]/div[1]/main/div/div/section/div/form/div[7]/div/div[2]')
    blockchain_button.click()
    polygon_button_location = '//span[normalize-space() = "Polygon"]'
    wait.until(ExpectedConditions.presence_of_element_located(
        (By.XPATH, polygon_button_location)))
    polygon_button = driver.find_element(
        By.XPATH, polygon_button_location)
    polygon_button.click()`

**Comment by VishnuPJ** [comment]
I have figured it out,

`blockchain_button = driver.find_element(By.XPATH, '//*[@id="__next"]/div[1]/main/div/div/section/div/form/div[7]/div/div[2]')`
`blockchain_button.click()`
`polygon_button_location = '//span[normalize-space() = "Polygon"]'`
`wait.until(ExpectedConditions.presence_of_element_located((By.XPATH, polygon_button_location)))`
`polygon_button = driver.find_element(By.XPATH, polygon_button_location)`
` polygon_button.click()`

**Comment by rizallk** [comment]
> 

where should i add the code?
